#ifndef XASH_ENGINE_SERVER_GAME_DLL_STRING_POOL_COMPAT_FORWARD_HPP
#define XASH_ENGINE_SERVER_GAME_DLL_STRING_POOL_COMPAT_FORWARD_HPP

#include "engine/server/game_dll/game_dll_string_pool_compat.hpp"

#endif
