#ifndef XASH_ENGINE_SERVER_GAME_DLL_VISIBILITY_TRACE_POLICY_FORWARD_HPP
#define XASH_ENGINE_SERVER_GAME_DLL_VISIBILITY_TRACE_POLICY_FORWARD_HPP

#include "engine/server/game_dll/game_dll_visibility_trace_policy.hpp"

#endif
