#ifndef XASH_ENGINE_SERVER_GAME_DLL_MESSAGE_SESSION_FORWARD_HPP
#define XASH_ENGINE_SERVER_GAME_DLL_MESSAGE_SESSION_FORWARD_HPP

#include "engine/server/game_dll/game_dll_message_session.hpp"

#endif
