#ifndef XASH_ENGINE_SERVER_GAME_DLL_MOVEMENT_POLICY_FORWARD_HPP
#define XASH_ENGINE_SERVER_GAME_DLL_MOVEMENT_POLICY_FORWARD_HPP

#include "engine/server/game_dll/game_dll_movement_policy.hpp"

#endif
