#ifndef XASH_ENGINE_SERVER_GAME_DLL_ENTITY_LIFECYCLE_FORWARD_HPP
#define XASH_ENGINE_SERVER_GAME_DLL_ENTITY_LIFECYCLE_FORWARD_HPP

#include "engine/server/game_dll/game_dll_entity_lifecycle.hpp"

#endif
