#ifndef XASH_ENGINE_SERVER_GAME_DLL_CLIENT_INFO_POLICY_FORWARD_HPP
#define XASH_ENGINE_SERVER_GAME_DLL_CLIENT_INFO_POLICY_FORWARD_HPP

#include "engine/server/game_dll/game_dll_client_info_policy.hpp"

#endif
