#ifndef XASH_ENGINE_SERVER_SERVER_CUSTOMIZATION_MESSAGE_FORWARD_HPP
#define XASH_ENGINE_SERVER_SERVER_CUSTOMIZATION_MESSAGE_FORWARD_HPP

#include "engine/server/messaging/server_customization_message.hpp"

#endif
