cmake_minimum_required(VERSION 3.16)
find_package(Threads REQUIRED)

xash3dpp_add_test(test_filesystem LIBS xash3dpp_filesystem Threads::Threads)
xash3dpp_add_test(test_file LIBS xash3dpp_filesystem)
xash3dpp_add_test(test_ci_directory LIBS xash3dpp_filesystem)
xash3dpp_add_test(test_backends LIBS xash3dpp_filesystem xash3dpp_miniz xash3dpp_memory)
