#!/usr/bin/env python

from waflib.extras import pthread

def options(opt):
	pass

def configure(conf):
	if not conf.env.DEST_OS in ['win32', 'android']:
		conf.check_pthreads(mode='c')

def build(bld):
	bld(name = 'modern_debugging_includes',
		export_includes = 'include')

	bld.stlib(target = 'modern_debugging',
		source = bld.path.ant_glob('debugging/*.cpp'),
		use = 'modern_debugging_includes werror')

	bld.stlib(target = 'modern_filesystem_debug',
		source = bld.path.ant_glob('filesystem/*.cpp'),
		use = 'modern_debugging modern_debugging_includes sdk_includes werror')

	if bld.env.TESTS:
		tests = {
			'debugging': '../tests/debugging/debugging.cpp',
			'filesystem_android_assets_backend': '../tests/filesystem/android_assets_backend.cpp',
			'filesystem_archive_registry': '../tests/filesystem/archive_registry.cpp',
			'filesystem_debug_snapshot': '../tests/filesystem/debug_snapshot.cpp',
			'filesystem_directory_backend': '../tests/filesystem/directory_backend.cpp',
			'filesystem_file_handle_ops': '../tests/filesystem/file_handle_ops.cpp',
			'filesystem_game_hierarchy_builder': '../tests/filesystem/game_hierarchy_builder.cpp',
			'filesystem_library_locator': '../tests/filesystem/library_locator.cpp',
			'filesystem_state': '../tests/filesystem/filesystem_state.cpp',
			'filesystem_path_policy': '../tests/filesystem/path_policy.cpp',
			'filesystem_pak_backend': '../tests/filesystem/pak_backend.cpp',
			'filesystem_registry_snapshot': '../tests/filesystem/registry_snapshot.cpp',
			'filesystem_search_result_builder': '../tests/filesystem/search_result_builder.cpp',
			'filesystem_wad_backend': '../tests/filesystem/wad_backend.cpp',
			'filesystem_zip_backend': '../tests/filesystem/zip_backend.cpp',
			'utilities_registry': '../tests/utilities/registry.cpp',
		}

		for i in tests:
			bld.program(features = 'test',
				source = tests[i],
				target = 'test_%s' % i,
				use = 'modern_filesystem_debug modern_debugging modern_debugging_includes sdk_includes werror PTHREAD',
				install_path = None)
