#!/usr/bin/env python

from waflib.extras import pthread

def options(opt):
	pass

def configure(conf):
	if not conf.env.DEST_OS in ['win32', 'android']:
		conf.check_pthreads(mode='c')

def build(bld):
	bld(name = 'modern_debugging_includes',
		export_includes = 'include')

	bld.stlib(target = 'modern_debugging',
		source = bld.path.ant_glob('debugging/*.cpp'),
		use = 'modern_debugging_includes werror')

	if bld.env.TESTS:
		tests = {
			'debugging': '../tests/debugging/debugging.cpp',
		}

		for i in tests:
			bld.program(features = 'test',
				source = tests[i],
				target = 'test_%s' % i,
				use = 'modern_debugging modern_debugging_includes werror PTHREAD',
				install_path = None)
