#!/usr/bin/env python

from waflib.extras import pthread

def options(opt):
	grp = opt.add_option_group('Game launcher options')

	grp.add_option('--disable-menu-changegame', action = 'store_true', dest = 'DISABLE_MENU_CHANGEGAME', default = False,
		help = 'disable changing the game from the menu [default: %(default)s]')

def configure(conf):
	if conf.env.DEST_OS == 'win32':
		conf.load('winres')

	if not conf.env.DEST_OS in ['win32', 'android']:
		conf.check_pthreads(mode='c')

	conf.define('XASH_DISABLE_MENU_CHANGEGAME', conf.options.DISABLE_MENU_CHANGEGAME)

def build(bld):
	bld(name = 'modern_debugging_includes',
		export_includes = 'include')

	bld.stlib(target = 'modern_debugging',
		source = bld.path.ant_glob('debugging/*.cpp'),
		use = 'modern_debugging_includes werror')

	launcher_sources = bld.path.ant_glob('launcher/*.cpp')

	if bld.env.DEST_OS == 'win32':
		launcher_sources += [
			'launcher/platform/library_win32.cpp',
			'launcher/platform/win32_argv.cpp',
		]
	else:
		launcher_sources += ['launcher/platform/library_posix.cpp']

	if bld.env.SAILFISH:
		launcher_sources += ['launcher/platform/environment_sailfish.cpp']
	else:
		launcher_sources += ['launcher/platform/environment_default.cpp']

	bld.stlib(target = 'modern_launcher',
		source = launcher_sources,
		use = 'modern_debugging_includes sdk_includes werror',
		export_includes = 'include')

	bld.stlib(target = 'modern_filesystem',
		source = bld.path.ant_glob('filesystem/*.cpp'),
		use = 'modern_debugging modern_debugging_includes sdk_includes werror')

	bld.stlib(target = 'modern_engine',
		source = bld.path.ant_glob('engine/**/*.cpp'),
		use = 'modern_debugging_includes werror',
		export_includes = 'include')

	if bld.env.LAUNCHER:
		source = ['launcher/platform/entry.cpp']
		linkflags = []

		if bld.env.DEST_OS == 'win32':
			source += ['../resources/launcher/windows/game.rc']

		# Half-Life 25th anniversary update doesn't have server library explicitly linked to libm
		if bld.env.DEST_OS == 'linux':
			linkflags += ['-Wl,--no-as-needed', '-lm']

		bld.program(source = source,
			target   = 'xash3d', # hl.exe
			use      = 'modern_launcher sdk_includes DL USER32 SHELL32 werror',
			linkflags = linkflags,
			rpath    = bld.env.DEFAULT_RPATH,
			install_path = bld.env.BINDIR,
			subsystem = bld.env.MSVC_SUBSYSTEM
		)

	if bld.env.TESTS:
		tests = {
			'debugging': '../tests/debugging/debugging.cpp',
			'engine_base_command_registry': '../tests/engine/base_command_registry.cpp',
			'engine_info_string': '../tests/engine/info_string.cpp',
			'filesystem_android_assets_backend': '../tests/filesystem/android_assets_backend.cpp',
			'filesystem_archive_registry': '../tests/filesystem/archive_registry.cpp',
			'filesystem_debug_snapshot': '../tests/filesystem/debug_snapshot.cpp',
			'filesystem_directory_backend': '../tests/filesystem/directory_backend.cpp',
			'filesystem_file_handle_ops': '../tests/filesystem/file_handle_ops.cpp',
			'filesystem_game_hierarchy_builder': '../tests/filesystem/game_hierarchy_builder.cpp',
			'filesystem_library_locator': '../tests/filesystem/library_locator.cpp',
			'filesystem_runtime': '../tests/filesystem/filesystem_runtime.cpp',
			'filesystem_state': '../tests/filesystem/filesystem_state.cpp',
			'filesystem_path_policy': '../tests/filesystem/path_policy.cpp',
			'filesystem_pak_backend': '../tests/filesystem/pak_backend.cpp',
			'filesystem_registry_snapshot': '../tests/filesystem/registry_snapshot.cpp',
			'filesystem_search_result_builder': '../tests/filesystem/search_result_builder.cpp',
			'filesystem_valve_path_resolver': '../tests/filesystem/valve_path_resolver.cpp',
			'filesystem_wad_backend': '../tests/filesystem/wad_backend.cpp',
			'filesystem_zip_backend': '../tests/filesystem/zip_backend.cpp',
			'launcher_application': '../tests/launcher/application.cpp',
			'launcher_engine_library': '../tests/launcher/engine_library.cpp',
			'launcher_launch_settings': '../tests/launcher/launch_settings.cpp',
			'utilities_registry': '../tests/utilities/registry.cpp',
		}

		for i in tests:
			bld.program(features = 'test',
				source = tests[i],
				target = 'test_%s' % i,
				use = 'modern_filesystem modern_launcher modern_engine modern_debugging modern_debugging_includes sdk_includes werror PTHREAD DL',
				install_path = None)
